apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multimodal-fashion-recommender
  namespace: mfs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: fashion.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: multimodal-fashion-recommender
                port:
                  number: 80
