apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mfs

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: mfs-als-config
    files:
      - als_model.yaml=../../config/als_model.yaml
  - name: mfs-assets-fetch-script
    files:
      - fetch_assets.sh=../../scripts/fetch_assets.sh

generatorOptions:
  disableNameSuffixHash: true
