apiVersion: apps/v1
kind: Deployment
metadata:
  name: multimodal-fashion-recommender
  namespace: mfs
spec:
  replicas: 2
  template:
    spec:
      initContainers:
        - $patch: replace
        - name: wait-assets
          image: alpine:3.20
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -lc
            - |
              until [ -f /work/data/.ready-d0.1.0 ] && [ -f /work/models/.ready-m0.1.0 ]; do
                echo "[wait-assets] waiting for mfs-sync-assets job..."
                sleep 5
              done
              echo "[wait-assets] assets ready"
          volumeMounts:
            - name: data-volume
              mountPath: /work/data
            - name: model-volume
              mountPath: /work/models
      volumes:
        - $patch: replace
        - name: data-volume
          persistentVolumeClaim:
            claimName: mfs-data-pvc
        - name: model-volume
          persistentVolumeClaim:
            claimName: mfs-models-pvc
        - name: als-config
          configMap:
            name: mfs-als-config
