apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mfs-models-pvc
  namespace: mfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: local-path
